# Generated by Django 4.2.6 on 2023-11-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
    ]
