# Generated by Django 4.2.6 on 2023-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_mainnews_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarybottomnews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='secondarytopnews',
            name='author',
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('news', 'News'), ('mainNews', 'MainNews'), ('secondaryNewsTop', 'SecondaryNewsTop'), ('secondayNewsBottom', 'SecondaryNewsBottom')], default='News', max_length=25),
        ),
        migrations.DeleteModel(
            name='MainNews',
        ),
        migrations.DeleteModel(
            name='SecondaryBottomNews',
        ),
        migrations.DeleteModel(
            name='SecondaryTopNews',
        ),
    ]
