# Generated by Django 4.2.6 on 2023-11-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_secondarybottomnews_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('Notícias', 'News'), ('Notícias principais', 'MainNews'), ('Notícias secundárias topo', 'SecondaryNewsTop'), ('Notícias secundárias baixo', 'SecondaryNewsBottom')], default='Notícias', max_length=26, verbose_name='Tipo'),
        ),
    ]
