# Generated by Django 4.2.6 on 2023-11-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('News', 'Notícias'), ('MainNews', 'Notícias principais'), ('SecondaryNewsTop', 'Notícias secundárias topo'), ('SecondaryNewsBottom', 'Notícias secundárias baixo')], default='Notícias', max_length=26, verbose_name='Tipo'),
        ),
    ]
