# Generated by Django 4.2.6 on 2023-11-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_qty_read_alter_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
