# Generated by Django 4.2.6 on 2023-11-27 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0002_alter_authorregister_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorregister',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='age',
            field=models.IntegerField(default='', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='current_city',
            field=models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará ', 'Pará '), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], default='', max_length=19, verbose_name='Current City'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='hometown',
            field=models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará ', 'Pará '), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], default='', max_length=19, verbose_name='Hometown'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='marital_status',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], default='', max_length=15, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='phone_number',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='profile_status',
            field=models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], default='', max_length=8, verbose_name='Profile Status'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='sex',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='', max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='username',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
