# Generated by Django 4.2.6 on 2023-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
    ]
