# Generated by Django 4.2.6 on 2023-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='Conteúdo'),
        ),
    ]
