# Generated by Django 4.2.6 on 2023-11-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
