# Generated by Django 4.2.6 on 2023-11-27 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0006_alter_community_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Community'},
        ),
        migrations.AlterField(
            model_name='community',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='community',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(upload_to='community/covers/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
